from typing import Final

REGXPR: Final[str]
TIMEFMT: Final[str]

def get_songs(songs: list) -> list: ...
def get_subsets(songs: list, num: int) -> list: ...
def to_json(result: tuple) -> str: ...
def to_text(result: tuple) -> str: ...
